apiVersion: v1
kind: Pod

metadata:
  name: storage-test

spec:
  containers:
  - name: app
    image: nginx

    volumeMounts:
    - name: data
      mountPath: /data

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: mysql-pvc