apiVersion: v1
kind: Pod
metadata:
  name: app-pod-ex2
spec:
  containers:
  - name: nginx
    image: nginx
    # command: ["sleep", "3600"]
    command: ["/bin/bash", "-c", "printenv && sleep 3600"] # by this container not exited immediate after complete task
    envFrom:
    - configMapRef:
        name: myapp
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: fname



