apiVersion: v1
kind: Pod
metadata:
  name: pod-config-ex1
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep", "3600"]
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: fname
    - name: LASTNAME
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: lname

# Using config map as a env var