apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    tire: backend
spec: #this spec is for deployment
  template:
    metadata:
      name: nginx
      labels:
        app: v1
    spec:
      containers:
        - name: nginx-container-dp
          image: nginx:1.23.0
  replicas: 3
  selector:
    matchLabels:
      app: v1
