apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
spec:
  type: ClusterIP # Optional (if not define it, By default service will create as clusterIP type svc)
  ports:
  - port: 80
    targetPort: 80
  selector:
    env: demo