apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-stress
    image: polinux/stress
    resources:
      requests:
        cpu: "100m"
        # memory:
      limits:
        cpu: "500m"
        # memory:
    command: ["stress"]
    args: ["--cpu", "5"]

# CPU current usages exceeds the limit -> which cause Spike in cpu(throttling)