apiVersion: v1
kind: Pod
metadata:
  name: pod-grey
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "10Mi"
          cpu: "250m"
        limits:
          memory: "12Mi"
          cpu: "500m"
  
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "blue"
