apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: demo

spec:
  initContainers:
  - name: init-myservice
    image: busybox:latest
    command: ['sh', '-c']
    args:
      - until nslookup myservice.default.svc.cluster.local; do echo waiting for the service; sleep 2; done
  containers:
  - name: myapp-container
    image: busybox:latest
    command: ['sh', '-c', 'echo the app is running && sleep 3600']
    env:
    - name: FIRST_NAME
      value: "Rahul"